#!/usr/bin/env python3
"""Initialize a Hermes profile council.

Creates Hermes profiles and profile-local workspace/reference skeletons.
It intentionally does not start gateways.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

HOME = Path.home()
HERMES_HOME = Path(os.environ.get("HERMES_HOME", HOME / ".hermes")).expanduser()
PROFILE_NAME_RE = re.compile(r"^[a-z][a-z0-9_-]{1,62}$")


def run(cmd: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, text=True, capture_output=True, check=check)


def profile_exists(name: str) -> bool:
    return (HERMES_HOME / "profiles" / name).exists()


def create_profile(name: str, clone_default: bool, dry_run: bool) -> None:
    if profile_exists(name):
        print(f"profile exists: {name}")
        return
    cmd = ["hermes", "profile", "create", name]
    if clone_default:
        cmd.append("--clone")
    if dry_run:
        print("would run:", " ".join(cmd))
        return
    print("creating profile:", name)
    res = run(cmd, check=False)
    if res.returncode != 0:
        sys.stderr.write(res.stderr or res.stdout)
        raise SystemExit(res.returncode)


def write_if_missing(path: Path, content: str, force: bool, dry_run: bool) -> None:
    if path.exists() and not force:
        print(f"kept existing: {path}")
        return
    if dry_run:
        print(f"would write: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote: {path}")


def profile_soul(name: str, council_name: str) -> str:
    title = name.replace("-", " ").replace("_", " ").title()
    return f"""# SOUL.md — {title}

## Active identity

You are `{name}`, a specialized Hermes profile in the `{council_name}` council.

Your exact role should be customized after discovery. Until then:

- Be concise, direct, and useful.
- Stay inside your specialty once defined.
- Preserve the user's language and technical terms.
- Ask for approval before external side effects.
- Do not start or manage messaging gateways unless explicitly asked.

## Hermes profile rules

- This is a Hermes profile, not an OpenClaw `agents/` folder.
- Profile workspace: `~/.hermes/profiles/{name}/workspace/{name}/`
- Put durable reusable workflows in Hermes skills, not ad-hoc notes.
- Use Hermes memory only for stable preferences/facts.

## Council coordination

- Use shared handoff docs under `workspace/{name}/handoffs/` when needed.
- For large standalone work, users can run:

```bash
hermes -p {name} chat
hermes -p {name} chat -q "your task"
```

## Hard safety rules

- No posting to social platforms without explicit permission.
- No sending email/messages without explicit permission.
- No payments, purchases, or destructive commands without explicit permission.
- No secrets in prompts, files, logs, or GitHub repos.
"""


def setup_profile(name: str, council_name: str, force: bool, dry_run: bool) -> None:
    base = HERMES_HOME / "profiles" / name
    workspace = base / "workspace" / name
    refs = base / "references" / "council-builder"
    for directory in [workspace, workspace / ".learnings", workspace / "handoffs", workspace / "outputs", refs]:
        if dry_run:
            print("would mkdir:", directory)
        else:
            directory.mkdir(parents=True, exist_ok=True)

    write_if_missing(base / "SOUL.md", profile_soul(name, council_name), force, dry_run)
    write_if_missing(
        base / "PROFILE.md",
        f"""# {name}

Hermes council profile generated by `hermes-council-builder`.

Run:

```bash
hermes -p {name} chat
hermes -p {name} chat -q "your task"
```

Workspace:

```text
~/.hermes/profiles/{name}/workspace/{name}/
```
""",
        force,
        dry_run,
    )
    write_if_missing(workspace / ".learnings" / "LEARNINGS.md", "# Learnings\n\nCorrections and reusable lessons for this profile.\n", False, dry_run)
    write_if_missing(workspace / ".learnings" / "ERRORS.md", "# Errors\n\nRepeated failures and their fixes.\n", False, dry_run)
    write_if_missing(workspace / ".learnings" / "FEATURE_REQUESTS.md", "# Feature Requests\n\nMissing capabilities requested by the user.\n", False, dry_run)
    write_if_missing(
        refs / "verification-checklist.md",
        f"""# Verification Checklist — {name}

- [ ] Output matches the requested format
- [ ] Claims are grounded in tools/context
- [ ] Side effects were approved
- [ ] No secrets or private data leaked
- [ ] Profile voice and boundaries respected
""",
        False,
        dry_run,
    )
    write_if_missing(refs / "council.json", json.dumps({"council": council_name, "profile": name}, indent=2) + "\n", False, dry_run)


def main() -> int:
    parser = argparse.ArgumentParser(description="Create Hermes profiles for a council of specialized agents.")
    parser.add_argument("--council-name", default="hermes-council")
    parser.add_argument("--profiles", nargs="+", required=True)
    parser.add_argument("--clone-default", dest="clone_default", action="store_true", default=True)
    parser.add_argument("--no-clone", dest="clone_default", action="store_false")
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    bad = [profile for profile in args.profiles if not PROFILE_NAME_RE.match(profile)]
    if bad:
        print("Invalid profile names:", ", ".join(bad), file=sys.stderr)
        print("Use lowercase names matching ^[a-z][a-z0-9_-]{1,62}$", file=sys.stderr)
        return 2

    for name in args.profiles:
        create_profile(name, args.clone_default, args.dry_run)
        setup_profile(name, args.council_name, args.force, args.dry_run)

    if not args.dry_run:
        res = run(["hermes", "profile", "list"], check=False)
        print(res.stdout)
    print("done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
